### ISSUE TITLE
Nest 10.x.x - Nest can't resolve dependencies of the DiscoveryService

### ISSUE THREAD

**Issue by AlecMMiller** [behnamnasehi/pigeon-mqtt-nestjs#4]
When attempting to use this library with a new project generated with the 10.1.7 CLI, the following error is thrown
```
[Nest] 20824  - 07/06/2023, 5:03:20 PM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the DiscoveryService (?, MetadataScanner). Please make sure that the argument ModulesContainer at index [0] is available in the DiscoveryModule context.

Potential solutions:
- Is DiscoveryModule a valid NestJS module?
- If ModulesContainer is a provider, is it part of the current DiscoveryModule?
- If ModulesContainer is exported from a separate @Module, is that module imported within DiscoveryModule?
  @Module({
    imports: [ /* the Module containing ModulesContainer */ ]
  })
```
Reverting to 9.x.x fixed the issue

**Comment by anaskhalidgg** [comment]
I am experiencing the same issue after upgrading NestJS to version 10.0.3.

**Comment by PiotrKasperski** [comment]
I've got the same problem

**Comment by kyozhou** [comment]
same issue, help...

**Comment by AlecMMiller** [comment]
While I wait for the PR to hopefully get approved and merged, I have a temporary package up with the NestJS dependencies bumped to support NestJS 10 here
https://www.npmjs.com/package/@alecmmiller/pigeon-mqtt-nest

**Comment by yangyingbiao** [comment]
> While I wait for the PR to hopefully get approved and merged, I have a temporary package up with the NestJS dependencies bumped to support NestJS 10 here https://www.npmjs.com/package/@alecmmiller/pigeon-mqtt-nest

I use the @alecmmiller/pigeon-mqtt-nest，but the same error occurred

**Comment by AlecMMiller** [comment]
> > While I wait for the PR to hopefully get approved and merged, I have a temporary package up with the NestJS dependencies bumped to support NestJS 10 here https://www.npmjs.com/package/@alecmmiller/pigeon-mqtt-nest
> 
> I use the @alecmmiller/pigeon-mqtt-nest，but the same error occurred

The issue is caused by having multiple versions of NestJS installed. First make sure there are no direct references to NestJS 9 in your package.json, if there aren't then look in your package.lock/yarn.lock/whatever for any references to NestJS 9. If there are, try running the appropriate commands to try to force reinstall everything, otherwise look into what's causing you to still have 9.x installed.

I suspect there's a better way to force only 10 be to installed with the package.json for this library, but I don't know enough to know how to do that. If this issue remains open longer I might end up looking into the issue more closely and set up my own fork of this project, and hopefully come up with a better solution.
